-- Seed data migrated from the Notion "Musical Instrument Repair" workspace.
-- Generated once on 2026-08-22. Re-running this file will duplicate rows --
-- it is NOT idempotent, so only run it against a freshly created database.
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO customers (id, notion_url, name, email, phone, address_line1, address_line2, city, state, zip, notes) VALUES
  (1, '1df5268c9d1580b8964afbc0f7f23ecc', 'Suzan Iscil', 'siscil2@cs.com', '571-225-1496', '2108 Donnington Ct.', NULL, 'Virginia Beach', 'VA', '23456', NULL),
  (2, '1df5268c9d158194965bf19604bf536d', 'Sharon Cooper', 'scooper1@cox.net', '7574997249', '416 Lavender Lane', NULL, 'Virginia Beac', 'VA', '23456', NULL),
  (3, '1e05268c9d158000a32cc4c5ac0c0a63', 'Eden Iscil', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  (4, '1e05268c9d15807c80c5d4e346435905', 'Lee Cooper', 'gleemon@gmail.com', '757-717-1385', '2108 Donnington Ct', NULL, 'Virginia Beach', 'VA', '23456', 'No notes - just a place to type!'),
  (5, '1e25268c9d158081a4d1e25042ff843f', 'Lee Cooper Clarinet', 'leecooperclarinet@gmail.com', '757-717-1385', NULL, NULL, NULL, NULL, NULL, NULL),
  (6, '3a45268c9d158008a6e3d079450068e9', 'Kristi Patton', NULL, '7576472696', '1993 SunDevil Drive', NULL, 'Virginia Beach', 'VA', '23464', NULL);

INSERT INTO technicians (id, notion_url, name, hourly_rate, specialty, availability) VALUES
  (1, '1dd5268c9d15812ba1d4e826ff4905c2', 'Lee', '35', 'Clarinet', NULL);

INSERT INTO parts_vendors (id, notion_url, name, website, street, city, state, zip, phone, email, account_number, notes) VALUES
  (1, '1dd5268c9d15811b856dea217067361a', 'Music Medic', 'https://www.musicmedic.com/', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  (2, '1e25268c9d15809ca3edfe5861416f4f', 'LCC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Items generated by Lee Cooper Clarinet'),
  (3, '1e25268c9d1580ca8f53f5599ce8d01c', 'Ferree’s Tools', 'https://www.ferreestoolsinc.com/', NULL, NULL, NULL, NULL, '800-253-2261', NULL, NULL, NULL);

INSERT INTO instruments (id, notion_url, name, type, make, model, serial, purchase_date, purchase_cost, valuation, owner_customer_id) VALUES
  (1, '1e25268c9d158053a512ea8e72954b23', 'Lee’s Concert Clarinet (184724)', 'Bb Clarinet', 'Buffet', 'R13', '184724', '1976-07-01', 800, 3500, 4),
  (2, '1e35268c9d158024b292e147a79a6bf0', 'Shop Use Only', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  (3, '1e35268c9d15807bbba1d95a616972ed', 'Metal MacDonald Clarinet', 'Bb Clarinet', 'Metal', 'n/a', 'n/a', '2025-02-01', 50, 50, 4),
  (4, '1e35268c9d158081af0ae06206229da9', 'Lee’s A Clarinet (151805)', 'A Clarinet', 'Buffet', 'R13', '151805', '1985-06-14', 800, 3500, 4),
  (5, '1e35268c9d1580ff920ce10bdc60ed4c', 'Lee’s Outdoor Clarinet (316191)', 'Bb Clarinet', 'Buffet', 'R13', '316191', '2022-04-27', 1300, 3500, 4),
  (6, '1e55268c9d158054998dc9e78dfe3136', 'Bundy (300287)', 'Bb Clarinet', 'Bundy', NULL, '300287', NULL, 0, 150, 5),
  (7, '1f25268c9d1580109597d679772709d1', 'Bundy (770410)', 'Bb Clarinet', 'Bundy', NULL, '770410', '2025-05-12', 30, 30, 5),
  (8, '3a45268c9d15807ca1b7f78842883f56', 'Patton-Bundy', 'Bb Clarinet', 'Bundy', 'Bundy', '1237630', '2026-07-21', 20, 120, 6);

INSERT INTO parts_inventory (id, notion_url, part_name, description, category, quantity_in_stock, reorder_level, reorder_cost, reorder_unit, reorder_url, markup, vendor_id) VALUES
  (1, '1dd5268c9d15817286c2d1d58993692d', 'MM-Medium Woven Pads (Each)', 'Medium Woven Bladder Pads', 'Pads', 100, 10, NULL, NULL, NULL, NULL, 1),
  (2, '1dd5268c9d1581e3a9eef5714dd2af09', 'Pad Set - Clarinet - Student (Basic)', 'Full Pad Set', 'Pads', 100, NULL, NULL, NULL, NULL, NULL, NULL),
  (3, '1e05268c9d158021809ac704283583c9', 'Shop Supplies', 'Misc Shop Supplies', 'Supplies', NULL, NULL, 4.99, 1, NULL, 1, 2),
  (4, '1e05268c9d15807588aacee3e62f9577', 'Other Supplies', 'Something Else', 'Supplies', 5, NULL, 3, NULL, NULL, 1, NULL),
  (5, '1e15268c9d1580598427da26aadb3713', 'Tech Cork', 'non-compressing material between adjustment points and under key feet.', 'Cork', NULL, NULL, NULL, NULL, 'https://www.musicmedic.com/techcork-sheets-125-mm-x-100-mm-sheets.html', NULL, 1),
  (6, '1e15268c9d158079b04fc4c24faad949', 'Tenon Cork', 'Precut tenon cork', 'Cork', NULL, NULL, 14.62, 10, 'https://www.musicmedic.com/bulk-clarinet-tenon-cork.html', 1.5, 1),
  (7, '1e15268c9d1580d7adf7e4bdb69a3598', 'Bb Clarinet Pad Set Medium Woven', 'MM - Medium Woven Pad Set', 'Pads', NULL, NULL, 31.07, 1, 'https://www.musicmedic.com/replacement-b-flat-clarinet-pad-set.html', 1.2, 1),
  (8, '1e25268c9d158001b9d8c54293652f4f', 'MM-Medium Pressed Set', 'MM-Medium Pressed Set', 'Pads', NULL, NULL, 34.81, 1, 'https://www.musicmedic.com/replacement-b-flat-clarinet-pad-set.html', 1.2, 1),
  (9, '1e25268c9d15801babc0da6078624c91', 'MM-Roo Pads', 'MM-Roo Pad Set', 'Pads', NULL, NULL, 49.2, 1, 'https://www.musicmedic.com/replacement-b-flat-clarinet-pad-set.html', 1.2, 1),
  (10, '1e25268c9d158029943cd34a45fd1d85', 'Pads-Feree B12', 'B12 White Synthetic Clarinet Pad Sets', 'Pads', NULL, NULL, 31.58, 1, 'https://www.ferreestoolsinc.com/collections/pads-1/products/b12-cls-pad-set?variant=30356937146415', 1.5, 3),
  (11, '1e25268c9d15808f81bfefec81c82dab', 'Ferree’s B70 Clarinet Pad Set', 'Feree’s B70 Clarinet', 'Pads', NULL, NULL, 37.7, 1, 'https://www.ferreestoolsinc.com/collections/pads-1/products/clarinet-sets-b70-series?variant=39709358817328', 1.2, 3),
  (12, '1e25268c9d1580b99ce2c0ef39a425f0', 'MM-Medium Woven Set', 'MM-Pad Medium Woven Pad Set', 'Pads', NULL, NULL, 31.0735, 1, 'https://www.musicmedic.com/replacement-b-flat-clarinet-pad-set.html', 1.2, 1),
  (13, '1e25268c9d1580c28b14e3d69a877d73', 'MM-Thin Pressed Set', 'MM-Thin Pressed Set', 'Pads', NULL, NULL, 31.07, 1, 'https://www.musicmedic.com/replacement-b-flat-clarinet-pad-set.html', 1.2, 1),
  (14, '1e25268c9d1580d28c26d39cf2ea4276', 'B21 Deluxe Double Skin Medium Clarinet', 'B21 Deluxe Double Skin Medium Clarinet', 'Pads', NULL, NULL, 2.09, 1, 'https://www.ferreestoolsinc.com/collections/pads-1/products/b21-clarinet-pad', 1.2, 3),
  (15, '1e25268c9d1580da886fd0eb923e7732', 'Mouthpiece Patch', 'Feree’s Q10 3M Silicone Mouthpiece Patch', 'Mouthpiece Patch', NULL, NULL, 10.28, 6, 'https://www.ferreestoolsinc.com/collections/small-items-1/products/q10-mouthpiece-patch?variant=40504746049584', 1.2, 3),
  (16, '1e25268c9d1580f8b399f8777c6cb718', 'B25 Soprano Clarinet pads', 'B25 Soprano Clarinet pads', 'Pads', NULL, NULL, 35, 1, 'https://www.ferreestoolsinc.com/collections/pads-1/products/b25-clarinet-pads', 1.2, 3),
  (17, '1e45268c9d1581918bd0d9f542759033', 'B 70 CLARINET SETS SERIES – Ferree\'s Tools Inc', NULL, 'Pads', NULL, NULL, NULL, NULL, 'https://www.ferreestoolsinc.com/collections/clarinet-pads-1/products/clarinet-sets-b70-series?variant=39709358751792', NULL, NULL),
  (18, '1e45268c9d1581dbb935e2a0cc943a71', 'Clarinet Pads – Ferree\'s Tools Inc', NULL, 'Pads', NULL, NULL, NULL, NULL, 'https://www.ferreestoolsinc.com/collections/clarinet-pads-1', NULL, NULL);

INSERT INTO repairs (id, notion_url, notion_repair_number, title, status, customer_id, instrument_id, technician_id, intake_date, estimated_completion, completion_date, estimated_repair_cost) VALUES
  (1, '1e25268c9d15805485a0f2dca6ec21e7', 24, 'Repair Ticket', 'Archive', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  (2, '1e25268c9d1580e48ac4e44ef2ce8a7c', 27, 'Repair Ticket', 'Archive', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  (3, '1e35268c9d158016bf33c1c5378dfd7d', 31, 'Repair Ticket', 'Archive', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  (4, '1e35268c9d15801b9d59f615b5216464', 30, 'Repair Ticket', 'Archive', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  (5, '1e05268c9d15805ba20dd7da6e43d680', 20, 'Repair Ticket', 'Archive', 3, NULL, NULL, '2025-04-27', NULL, NULL, NULL),
  (6, '1e05268c9d15807fb76de5bddc0cdac4', 11, 'Repair Ticket', 'Archive', 5, NULL, 1, '2025-04-25', '2025-05-02', NULL, NULL),
  (7, '1e05268c9d1580bfa638e4ddd29e1c56', 17, 'Repair Ticket', 'Archive', 2, NULL, 1, '2025-04-25', '2025-05-09', NULL, NULL),
  (8, '1e25268c9d1580d0abf1e21e6774c2a4', 26, 'Tenon Corks', 'Complete', 4, 1, NULL, NULL, NULL, NULL, NULL),
  (9, '1e25268c9d1580daa3f4df97187aae6f', 28, 'Repair Ticket', 'Complete', 4, 1, 1, NULL, '2025-04-30', NULL, NULL),
  (10, '1e25268c9d1580ea894de79644842d15', 25, 'Shop Use', 'Hold - Parts', 5, 2, NULL, NULL, NULL, NULL, NULL),
  (11, '1e35268c9d1580a4a5d9f11fff4a222d', 29, 'Repair Ticket', 'Complete', 4, 5, 1, '2025-04-20', NULL, NULL, NULL),
  (12, '1e55268c9d158053aebae4fd45c65a6d', 32, 'Full Overhaul', 'Complete', 5, 6, 1, NULL, '2026-04-30', NULL, NULL),
  (13, '1f25268c9d1580d78f90e7389f19261c', 33, 'FBMarketplace Clarinet Intake', 'Complete', 5, 7, 1, NULL, '2025-08-01', NULL, NULL),
  (14, '3a45268c9d15801e9ac5c717ee32baa4', 34, 'Corks, make play (Patton)', 'Ready for Pickup', 6, 8, 1, '2026-07-27', '2026-07-29', NULL, NULL);

INSERT INTO invoices (id, notion_url, notion_invoice_number, name, repair_id, invoice_date, due_date, payment_status, tax_rate) VALUES
  (1, '3a45268c9d15809eb54afb7951dd0b5c', 4, 'Invoice for Full Overhaul', 12, '2026-07-21', NULL, 'Unpaid', NULL),
  (2, '3b15268c9d1580098f41c930e0a93775', 5, 'Invoice for FBMarketplace Clarinet Intake', 13, '2026-08-02', NULL, 'Unpaid', NULL);

-- The tables above use fixed ids carried over from Notion (so foreign keys
-- migrated exactly), but their id columns are AUTO_INCREMENT so the app can
-- insert new rows going forward. Bump each counter past the highest migrated
-- id so the next INSERT doesn't collide with Notion-sourced rows.
ALTER TABLE customers AUTO_INCREMENT = 7;
ALTER TABLE technicians AUTO_INCREMENT = 2;
ALTER TABLE parts_vendors AUTO_INCREMENT = 4;
ALTER TABLE instruments AUTO_INCREMENT = 9;
ALTER TABLE parts_inventory AUTO_INCREMENT = 19;
ALTER TABLE repairs AUTO_INCREMENT = 15;
ALTER TABLE invoices AUTO_INCREMENT = 3;

INSERT INTO work_log (notion_url, label, repair_id, technician_id, start_work, end_work, time_on_repair, billable) VALUES
  ('1de5268c9d1580378bdad313f3d2b7b1', 'Labor Cost', 8, 1, '2025-04-23 01:55:00', NULL, 1, 1),
  ('1df5268c9d1580a198e4fb4803ab9b3b', 'Labor Cost', 6, 1, '2025-04-24 22:01:00', NULL, 1, 1),
  ('1df5268c9d1580f3b418de96278a8140', 'Labor Cost', 6, 1, '2025-04-24 20:44:00', NULL, 1, 1),
  ('1e05268c9d1580828ac7f7e3a134ad3f', 'Labor Cost', 6, 1, '2025-04-25 16:50:00', NULL, 1, 1),
  ('1e05268c9d1580ae9417f119874acbef', 'Labor Cost', 7, 1, '2025-04-25 22:37:00', NULL, 1, 1),
  ('1e25268c9d15806dac7ad0351a8c29d8', 'Labor Cost', 6, 1, '2025-04-27 19:59:00', NULL, 1, 1),
  ('1e55268c9d1580a38487d19ff185350b', 'Labor Cost', 12, 1, '2025-04-28 16:47:00', NULL, 1.5, 1),
  ('1e55268c9d1580bf9bd6ecbcda4fb1cf', 'Overhaul', 12, 1, '2025-04-29 16:51:00', NULL, 2, 1),
  ('1f15268c9d15804989e8ee2337dfae29', 'Remove - Clean - Prep for repad', 12, 1, '2025-05-03 16:03:00', NULL, 2, 1),
  ('1f15268c9d1580a78331dff967ec5eaf', 'Repad - Upper', 12, 1, '2025-05-12 16:05:00', NULL, 2, 1),
  ('2125268c9d15801a96fcc66d4edc80f9', 'Repad - Adjust Upper Joint', 12, 1, '2025-06-14 16:34:00', NULL, 1, 1),
  ('3a95268c9d158052bed2c88d62d72a8e', 'Disassemble and Clean Body - Ready for repairs', 14, 1, '2026-07-26 18:35:00', '2026-07-26', 1, 1),
  ('3aa5268c9d1580f193d4c29c1ba00ccb', 'Labor Cost', NULL, 1, '2026-07-27 16:20:00', NULL, 1, NULL),
  ('3b05268c9d1580778865e5e986f99798', NULL, NULL, 1, '2026-08-02 14:07:00', NULL, 1, NULL),
  ('3b15268c9d15803c9fe3d0a815922d31', 'Full Repad', 14, 1, '2026-07-31 00:31:00', '2026-08-02', 4, 1);

INSERT INTO parts_used (notion_url, label, part_id, repair_id, quantity_used, customer_cost, date_used) VALUES
  ('1e05268c9d158003b3bffb123663e023', 'Parts and Supplies', 11, 7, 3, 56.55, NULL),
  ('1e05268c9d15808283ebc7c1a70bbe9f', 'Parts and Supplies', NULL, 10, 1, 5, NULL),
  ('1e05268c9d1580c681c7ce9eba02319a', 'Parts and Supplies', 7, 6, 1, 46.61, NULL),
  ('1e05268c9d1580d9959fe6a32fa4f079', 'Parts and Supplies', 7, 6, 1, 46.61, NULL),
  ('1e05268c9d1580ec80abcc6aff07f928', 'Parts and Supplies', 8, 7, 1, 52.22, NULL),
  ('1e05268c9d1580eda11fd2695a0cc9be', 'Parts and Supplies', 7, 6, 1, 46, NULL),
  ('1e55268c9d158066bea6c78e8f95d6c1', 'Parts and Supplies', 12, 12, 1, NULL, '2025-04-28'),
  ('1f25268c9d1580bf8a68c73d52a548fc', 'Parts and Supplies', NULL, 12, NULL, NULL, NULL),
  ('3b15268c9d1580569aa4fc1356277e39', 'Woven - Pad Set (Bundy)', 12, 14, 1, 35, NULL);

INSERT INTO repair_tags (notion_url, tag_title, repair_id) VALUES
  ('3aa5268c9d158098967dd174563323f7', 'New Repair Ticket', 14),
  ('3aa5268c9d1580b8bc75c25f79b706f1', 'New Repair Ticket', 14),
  ('3aa5268c9d1581129f29ef362e640f4a', 'New Repair Tag', NULL);

INSERT INTO receipts (notion_url, receipt_title, repair_id) VALUES
  ('3aa5268c9d15800698d6cf00b7649bc2', 'Estimate and Receipt', 14),
  ('3aa5268c9d15804f843be383958bcb71', 'Estimate and Receipt', 14);

SET FOREIGN_KEY_CHECKS=1;
